openapi: 3.1.1
info:
  title: Pet Clinic
  description: Pet clinic
  version: 0.0.1
paths:
  /petclinic/pets:
    get:
      summary: Get searched pets.
      operationId: getPets
      parameters:
        - name: ids
          in: query
          description: IDs of pets to be searched.
          schema:
            type: array
            uniqueItems: true
            minItems: 1
            items:
              type: string
              format: uuid
        - name: names
          in: query
          description: Names of pets to be searched.
          schema:
            type: array
            uniqueItems: true
            minItems: 1
            items:
              type: string
        - name: pageNumber
          in: query
          description: Zero-based page index.
          required: true
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: pageSize
          in: query
          description: Page size.
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        200:
          description: Found pets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetPageDto'
    post:
      summary: Create a new pet.
      operationId: createPet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetCreateDto'
      responses:
        201:
          description: Created pet.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetDto'
  /petclinic/pets/{id}:
    patch:
      summary: Patch a pet.
      operationId: patchPet
      parameters:
        - name: id
          in: path
          required: true
          description: Pet ID.
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetPatchDto'
      responses:
        200:
          description: Patched pet.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetDto'
        404:
          description: Pet not found.
    put:
      summary: Update a pet.
      operationId: updatePet
      parameters:
        - name: id
          in: path
          required: true
          description: Pet ID.
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetUpdateDto'
      responses:
        200:
          description: Updated pet.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetDto'
        404:
          description: Pet not found.
    delete:
      summary: Delete a pet.
      operationId: deletePet
      parameters:
        - name: id
          in: path
          required: true
          description: Pet ID.
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Pet deleted.
        404:
          description: Pet not found.
components:
  schemas:
    PetCreateDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Pet name.
          minLength: 1
          maxLength: 255
          pattern: '^\S(.*\S)?$'
    PetUpdateDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Pet name.
          minLength: 1
          maxLength: 255
          pattern: '^\S(.*\S)?$'
    PetPatchDto:
      type: object
      properties:
        name:
          type: string
          description: Pet name.
          minLength: 1
          maxLength: 255
          pattern: '^\S(.*\S)?$'
    PetPageDto:
      type: object
      required:
        - items
        - pageNumber
        - pageSize
        - totalElements
        - totalPages
      properties:
        items:
          type: array
          description: Page items.
          items:
            $ref: '#/components/schemas/PetDto'
        pageNumber:
          type: integer
          description: Zero-based page index.
          minimum: 0
        pageSize:
          type: integer
          description: Page size.
          minimum: 1
          maximum: 100
        totalElements:
          type: integer
          description: Total number of matching pets.
          format: int64
          minimum: 0
        totalPages:
          type: integer
          description: Total number of pages.
          minimum: 0
    PetDto:
      type: object
      required:
        - id
        - name
        - createdAt
        - lastModifiedAt
      properties:
        id:
          type: string
          description: Pet ID.
          format: uuid
        name:
          type: string
          description: Pet name.
        createdAt:
          type: string
          format: date-time
          description: Pet creation timestamp.
        lastModifiedAt:
          type: string
          format: date-time
          description: Pet last modification timestamp.
